spring:
  application:
    name: customers-api
  cloud:
    config:
      server:
        native:
          searchLocations: file:///etc/config/secrets/default

server:
  port: 8080
jwt:
  secret: mocsecurity

secrets:
  filePath: file:///etc/config/secrets/default

spring:
  jpa:
    hibernate:
      ddl-auto: none

# ******************* Tomcat Access logs configuration ***************
server:
  tomcat:
    accesslog:
      enabled: true
      basedir: tomcat
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: '{ "clientip":"%h", "log_date":"%t", "rawrequest_str":"%r", "response_int":%s, "bytes_int":%B, "response_time_int":%D, "referrer_stn":"%{Referer}i", "agent_stn":"%{User-agent}i", "X-B3-TraceId":"%{X-B3-TraceId}i", "X-B3-SpanId":"%{X-B3-SpanId}i", "X-B3-ParentSpanId":"%{X-B3-ParentSpanId}i" }'
